using System.Threading.Tasks;
using Scopos.BabelFish.DataModel.OrionMatch;

namespace Scopos.BabelFish.Tests.OrionMatch {

    [TestClass]
    public class MatchHtmlReportTests : BaseTestClass {

        public static string ExpectedContent = """
            <div>            
                <h1>Haughton AFJROTC Tops Southwestern Randolph AJROTC for Fourth Consecutive Win</h1>
                <p>
                Haughton AFJROTC secured a decisive 1060.8-983.5 victory over Southwestern Randolph AJROTC in Week 7 action of the <a href="https://rezults.scopos.tech/league/1.1.2025071411011185.3/?src=press-release">2025 National Sporter Air Rifle League</a>. With postseason seeding coming into sharp focus and just one regular season contest remaining, each result carries added significance for companies competing in this national three-position air rifle league featuring high school and junior club teams.
                </p>
                <p>
                Guided by coach Tony Zucco, <a href="https://rezults.scopos.tech/league/1.1.2025071411011185.3/team/Haughton%20AFJROTC/?src=press-release">Haughton AFJROTC</a> from Haughton, La., notched its fourth straight win to move to 4-2. Chris Fick led the team with a score of 283.5, while teammates Emily Wood, Ethan Evans, and Taylor McCord delivered strong performances to contribute to the week’s total. Haughton continues to hold first place in the Champions Division, AFJROTC & SFJROTC conference, and looks to maintain momentum as postseason brackets take shape.
                </p>
                <p>
                <a href="https://rezults.scopos.tech/league/1.1.2025071411011185.3/team/Southwestern%20Randolph%20AJROTC/?src=press-release">Southwestern Randolph AJROTC</a> of Asheboro, N.C., coached by Chris Sikes, now stands at 3-3. The squad was paced by Riley Clapp’s 267.7, followed by scores from Holden Deaton, Davis Miller, and Madison Ligon. Despite the defeat, Southwestern Randolph maintains the top spot in the Elite Division, AJROTC conference standings as they prepare for the season’s final match.
                </p>
                <p>
                Haughton AFJROTC seized the advantage early, holding a six-point edge after the kneeling stage. Their lead ballooned to 39.1 points following the prone segment, commonly viewed as the most consistent position for shooters. By the conclusion of the standing portion—often challenging even for experienced athletes—Haughton’s advantage grew to a commanding 77.3 points, with standout individual scores driving their win.
                </p>
                <p>
                In the final week of the regular season, Haughton AFJROTC (4-2) is set for a key matchup with Mechanicsville NJROTC (4-2), while Southwestern Randolph AJROTC (3-3) will take on Palmetto Ridge High AJROTC (4-2). As the National Sporter Air Rifle League nears its postseason, both division standing and next season’s divisional placement will be determined by these final contests.
                </p>
                <p>
                <a href="https://rezults.scopos.tech/game/1.1.2025110314542689.1/?src=press-release">Box Score</a> | 
                <a href="https://rezults.scopos.tech/league/1.1.2025071411011185.3/team/Haughton%20AFJROTC/?src=press-release">Haughton AFJROTC Team Page</a> | 
                <a href="https://rezults.scopos.tech/league/1.1.2025071411011185.3/team/Southwestern%20Randolph%20AJROTC/?src=press-release">Southwestern Randolph AJROTC Team Page</a>
                </p>
            </div>

            <p>This press release was in part generated by artificial intelligence maintained by <a href="https://www.scopos.tech">Scopos LLC</a>.</p>
            """;

        [TestMethod]
        public async Task SadPathFactoryAsync() {

            //Made up Match ID, should fail
            var mId = new MatchID( "1.1000.12345678.1" );

            var report = await MatchHtmlReport.FactoryAsync( mId );

            Assert.IsNotNull( report );
            Assert.AreEqual( $"https://cdn.scopos.tech/matches/{mId}/pressrelease.html", report.Uri );
            Assert.AreEqual( string.Empty, report.Title );
            Assert.IsFalse( await report.IsValidUriAsync() );
            Assert.AreEqual( string.Empty, await report.GetHtmlReportAsync() );
        }

        [TestMethod]
        public async Task HappyPathFactoryAsync() {

            //eEal Match ID, should work
            var mId = new MatchID( "1.1.2025110314542689.1" );

            var report = await MatchHtmlReport.FactoryAsync( mId );

            Assert.IsNotNull( report );
            Assert.AreEqual( $"https://cdn.scopos.tech/matches/{mId}/pressrelease.html", report.Uri );
            Assert.AreEqual( "Haughton AFJROTC Tops Southwestern Randolph AJROTC for Fourth Consecutive Win", report.Title );
            Assert.IsTrue( await report.IsValidUriAsync() );
            Assert.AreNotEqual( string.Empty, await report.GetHtmlReportAsync() );
        }
    }
}
