using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Text;
using System.Threading.Tasks;
using Scopos.BabelFish.Runtime;
using Scopos.BabelFish.Tests;
using Scopos.BabelFish.Requests.AthenaTarget;
using Scopos.BabelFish.DataModel.AthenaTarget;
using Scopos.BabelFish.APIClients;
using Scopos.BabelFish.Runtime.Authentication;

namespace Scopos.BabelFish.Tests.AthenaTarget {

    [TestClass]
    public class LoginTest {

        /// <summary>
        /// Unit test to confirm the Constructors set the api key and API stage as expected.
        /// </summary>
        [TestMethod]
        public void BasicConstructorTests() {

            var defaultConstructorClient = new AthenaTargetAPIClient( Constants.X_API_KEY );
            var apiStageConstructorClient = new AthenaTargetAPIClient( Constants.X_API_KEY, APIStage.BETA );

            Assert.AreEqual( Constants.X_API_KEY, defaultConstructorClient.XApiKey );
            Assert.AreEqual( APIStage.PRODUCTION, defaultConstructorClient.ApiStage );

            Assert.AreEqual( Constants.X_API_KEY, apiStageConstructorClient.XApiKey );
            Assert.AreEqual( APIStage.BETA, apiStageConstructorClient.ApiStage );
        }

        [TestMethod]
        public async Task LoginToTargetHappyPath() {

            var client = new AthenaTargetAPIClient( Constants.X_API_KEY, APIStage.ALPHA );

            //Test Dev 3 is associated with something ...
            var userAuthentication = new UserAuthentication(
                Constants.TestDev3Credentials.Username,
                Constants.TestDev3Credentials.Password );
            var authCode = "5088a1"; //Generated by the user when logging in.
            var request = new AthenaEmployLoginCodeAuthenticatedRequest( authCode, userAuthentication );

            var response = await client.AthenaEmployLoginCodeAuthenticatedAsync( request );

            Assert.AreEqual( System.Net.HttpStatusCode.OK, response.StatusCode );

            var estTarget = response.Value.ThingName;
            var loggedInUserId = response.Value.Session.User.UserID;

            Assert.AreEqual( estTarget, "ESTTarget-000000001" );

            Assert.AreEqual( Constants.TestDev3UserId, loggedInUserId );

        }

        [TestMethod]
        public async Task LoginToTargetSadPath() {

            var client = new AthenaTargetAPIClient( Constants.X_API_KEY, APIStage.ALPHA );

            //Test Dev 3 is associated with something ...
            var userAuthentication = new UserAuthentication(
                Constants.TestDev3Credentials.Username,
                Constants.TestDev3Credentials.Password );
            var authCode = "fakecode";
            var request = new AthenaEmployLoginCodeAuthenticatedRequest( authCode, userAuthentication );

            var response = await client.AthenaEmployLoginCodeAuthenticatedAsync( request );

            //When the auth code is wrong, unknown, or expired, and 404 is returned.
            Assert.AreEqual( System.Net.HttpStatusCode.NotFound, response.StatusCode );

            //The message list dhould incldue the message it's expired or invalid.
            var message = response.MessageResponse.Message[0];
            Assert.IsTrue( message.Contains( "not recognized, expired or is invalid" ) );

        }
    }
}
