using Scopos.BabelFish.APIClients;
using Scopos.BabelFish.DataActors.ResultListMerger;
using Scopos.BabelFish.DataModel.Definitions;

namespace Scopos.BabelFish.DataModel.OrionMatch {

    /// <summary>
    /// Describes a Result List that is generated by merging (or combining) the results from multiple other Result Lists.
    /// <para>The action of merging a result list is done by the <see cref="ResultListMergerEngine"/>.</para>
    /// </summary>
    public class MergedResultList :
        IGetScoreFormatCollectionDefinition,
        G_STJ_SER.IJsonOnDeserialized,
        G_STJ_SER.IJsonOnDeserializing {

        #region Private Variables
        private bool _ignoreEvents = false;
        #endregion

        #region Constructors
        /// <summary>
        /// Public Constructor.
        /// <para>Unless you are a deserializer, it is generally best to construct a new instance
        /// using the <see cref="CreateAsync(string, MergeMethodType)"/> method, as this sets the configuration property <see cref="Configuration"/>.</para>
        /// </summary>
        public MergedResultList() { }

        /// <summary>
        /// This is the preferred method for creating a new instance of MergedResultList. This method sets the <see cref="Method"/> property,
        /// and also initializes the <see cref="Configuration"/> property with a new instance of the appropriate type based on the MergeMethodType specified.
        /// </summary>
        /// <param name="resultListName">The name of the result list.</param>
        /// <param name="mergeMethodType">The type of merge method to use.</param>
        /// <returns>A new instance of <see cref="MergedResultList"/>.</returns>
        public static async Task<MergedResultList> CreateAsync( IMergedResultListContainer container, string resultListName, MergeMethodType mergeMethodType ) {

            /*
             * Even though this method is asynchronous, there are currently no asynchronous calls within it. However, 
             * it is possible that in the future, we may want to add asynchronous calls (e.g. to fetch default configuration from an API), 
             * so we will keep the async signature to avoid breaking changes in the future.
             */

            MergedResultList mrl = new MergedResultList() {
                Method = mergeMethodType,
                ResultName = resultListName,
                Container = container
            };

            switch (mergeMethodType) {
                case MergeMethodType.SUM:
                    mrl.Configuration = new SumMethodConfiguration();
                    break;
                case MergeMethodType.AVERAGE:
                    mrl.Configuration = new AverageMethodConfiguration();
                    break;
                case MergeMethodType.REENTRY:
                    mrl.Configuration = new ReentryMethodConfiguration();
                    break;
            }

            return mrl;
        }

        /// <summary>
        /// This method is called after deserialization with System.Text.Json. 
        /// </summary>
        public void OnDeserialized() {

            _ignoreEvents = false;
        }

        /// <summary>
        /// Method is called before deserialization with System.Text.Json.
        /// </summary>
        public void OnDeserializing() {

            _ignoreEvents = true;
        }
        #endregion

        #region Event Handlers
        /// <summary>
        /// Gets invoked when a new ResultListMember is added to this MergedResultList's ResultListMembers collection. The event args include the ResultListMember that was added.
        /// </summary>
        public event EventHandler<EventArgs<ResultListMember>> OnResultListMemberAdded;

        #endregion

        #region Data Model Properties

        /// <summary>
        /// The human readable name of this Result List
        /// </summary>
        [G_NS.JsonProperty( Order = 1 )]
        public string ResultName { get; set; } = string.Empty;

        /// <summary>
        /// Globally unique identifier assigned to this MergedResultList.
        /// <para>String formatted as a UUID.</para>
        /// <para>Its is a fantastically bad idea to change this value after Construction.</para>
        /// </summary>
        [G_NS.JsonProperty( Order = 2 )]
        public string MergedId { get; set; } = Guid.NewGuid().ToString();

        /// <summary>
        /// The Tournament Method identifier to use to merge this Result List.
        /// </summary>
        [G_NS.JsonProperty( Order = 3 )]
        public MergeMethodType Method { get; set; } = MergeMethodType.SUM;

        /// <summary>
        /// The list of Result Lists (in the form of <see cref="ResultListMember"/> to pull data from for this MergedResultList.
        /// </summary>
        [G_NS.JsonProperty( Order = 6 )]
        public List<ResultListMember> ResultListMembers { get; set; } = new List<ResultListMember>();

        /// <summary>
        /// Method specific Configuration
        /// </summary>
        [G_NS.JsonProperty( Order = 7 )]
        public MergeConfiguration Configuration { get; set; }

        #endregion

        #region Helper Properties
        /// <summary>
        /// Backwards pointer to the <see cref="MatchStructure"/> or <see cref="Tournament"/> (both of which implement the <see cref="IMergedResultListContainer"/> interface)
        /// that is holding this MergedResultList. Populated on deserialization.
        /// </summary>
        [G_NS.JsonIgnore]
        public IMergedResultListContainer Container { get; internal set; }
        #endregion

        #region Methods
        /// <summary>
        /// Adds a new ResultListMember instance, based on the passed in ResultListAbbr, to the ResultListMembers collection of this MergedResultList. Also invokes the <see cref="OnResultListMemberAdded"/> event.
        /// </summary>
        /// <param name="resultList"></param>
        /// <returns></returns>
        /// <exception cref="ArgumentNullException"></exception>
        public async Task<ResultListMember> AddResultListMemberAsync( ResultListAbbr? resultList ) {
            if (resultList is null) {
                throw new ArgumentNullException( nameof( resultList ) );
            }

            var resultListMember = new ResultListMember();
            resultListMember.MatchId = this.Container.MatchId;
            resultListMember.CourseOfFireId = resultList.CourseOfFireId;
            resultListMember.ResultName = resultList.ResultName;
            resultListMember.HeaderName = resultList.EventName;

            this.ResultListMembers.Add( resultListMember );

            if (!_ignoreEvents) {
                this.OnResultListMemberAdded?.Invoke( this, new EventArgs<ResultListMember>( resultListMember ) );
            }

            return resultListMember;
        }

        /// <inheritdoc />
        /// <exception cref="XApiKeyNotSetException" />
        /// <exception cref="DefinitionNotFoundException" />
        /// <exception cref="ScoposAPIException" />
        public async Task<ScoreFormatCollection> GetScoreFormatCollectionDefinitionAsync() {
            return await DefinitionCache.GetScoreFormatCollectionDefinitionAsync( this.Configuration.ScoreFormatCollectionDef );
        }

        #endregion
    }
}
