using Scopos.BabelFish.APIClients;
using Scopos.BabelFish.DataActors.Tournaments;
using Scopos.BabelFish.DataModel.Definitions;

namespace Scopos.BabelFish.DataModel.OrionMatch {

    /// <summary>
    /// Describes a Result List that is generated by merging (or combining) the results from multiple other Result Lists.
    /// <para>The action of merging a result list is done by the <see cref="TournamentMerger"/>.</para>
    /// </summary>
    public class MergedResultList : IGetScoreFormatCollectionDefinition {

        /// <summary>
        /// Globally unique identifier assigned to this MergedResultList.
        /// <para>The SQL table tournament_merged_result_list assigns this value.</para>
        /// <para>A value of 0 means a value hasn't been assigned yet.</para>
        /// </summary>
        [G_NS.JsonProperty( Order = 1 )]
        public int MergedId { get; set; } = 0;

        /// <summary>
        /// The human readable name of this Result List
        /// </summary>
        [G_NS.JsonProperty( Order = 2 )]
        public string ResultName { get; set; } = string.Empty;

        /// <summary>
        /// The Tournament Method identifier to use to merge this Result List.
        /// </summary>
        [G_NS.JsonProperty( Order = 3 )]
        public string Method { get; set; } = string.Empty;

        /// <summary>
        /// The SCORE FORMAT COLLECTION to use while displaying scores for this MergedResultList
        /// </summary>
        [G_NS.JsonProperty( Order = 4 )]
        [Obsolete( "Use .Configuration.ScoreFormatCollectionDef instead." )]
        public SetName ScoreFormatCollectionDef { get; set; } = SetName.Parse( "v1.0:orion:Standard Score Formats" );

        /// <summary>
        /// The ScoreConfigName to use, from the SCORE FORMAT COLLECTION, while displaying scores for this MergedResultList
        /// </summary>
        [G_NS.JsonProperty( Order = 5 )]
        [Obsolete( "Use .Configuration.ScoreConfigName instead." )]
        public string ScoreConfigName { get; set; } = "Decimal";

        /// <summary>
        /// The list of Result Lists (in the form of <see cref="ResultListMember"/> to pull data from for this MergedResultList.
        /// </summary>
        [G_NS.JsonProperty( Order = 6 )]
        public List<ResultListMember> ResultListMembers { get; set; } = new List<ResultListMember>();

        /// <summary>
        /// Method specific Configuration
        /// </summary>
        [G_NS.JsonProperty( Order = 7 )]
        public MergeConfiguration Configuration { get; set; }

        /// <inheritdoc />
        /// <exception cref="XApiKeyNotSetException" />
        /// <exception cref="DefinitionNotFoundException" />
        /// <exception cref="ScoposAPIException" />
        public async Task<ScoreFormatCollection> GetScoreFormatCollectionDefinitionAsync() {
            return await DefinitionCache.GetScoreFormatCollectionDefinitionAsync( this.Configuration.ScoreFormatCollectionDef );
        }
    }
}
