using Scopos.BabelFish.APIClients;
using Scopos.BabelFish.DataActors.ResultListMerger;
using Scopos.BabelFish.DataModel.Definitions;

namespace Scopos.BabelFish.DataModel.OrionMatch {

    /// <summary>
    /// Describes a Result List that is generated by merging (or combining) the results from multiple other Result Lists.
    /// <para>The action of merging a result list is done by the <see cref="ResultListMergerEngine"/>.</para>
    /// </summary>
    public class MergedResultList : IGetScoreFormatCollectionDefinition {

        #region Private Variables

        #endregion

        #region Constructors
        /// <summary>
        /// Public Constructor.
        /// <para>Unless you are a deserializer, it is generally best to construct a new instance
        /// using the <see cref="CreateAsync(string, MergeMethodType)"/> method, as this sets the configuration property <see cref="Configuration"/>.</para>
        /// </summary>
        public MergedResultList() { }

        /// <summary>
        /// This is the preferred method for creating a new instance of MergedResultList. This method sets the <see cref="Method"/> property,
        /// and also initializes the <see cref="Configuration"/> property with a new instance of the appropriate type based on the MergeMethodType specified.
        /// </summary>
        /// <param name="resultListName">The name of the result list.</param>
        /// <param name="mergeMethodType">The type of merge method to use.</param>
        /// <returns>A new instance of <see cref="MergedResultList"/>.</returns>
        public static async Task<MergedResultList> CreateAsync( IMergedResultListContainer container, string resultListName, MergeMethodType mergeMethodType ) {

            /*
             * Even though this method is asynchronous, there are currently no asynchronous calls within it. However, 
             * it is possible that in the future, we may want to add asynchronous calls (e.g. to fetch default configuration from an API), 
             * so we will keep the async signature to avoid breaking changes in the future.
             */

            MergedResultList mrl = new MergedResultList() {
                Method = mergeMethodType,
                ResultName = resultListName,
                Container = container
            };

            switch (mergeMethodType) {
                case MergeMethodType.SUM:
                    mrl.Configuration = new SumMethodConfiguration();
                    break;
                case MergeMethodType.AVERAGE:
                    mrl.Configuration = new AverageMethodConfiguration();
                    break;
                case MergeMethodType.REENTRY:
                    mrl.Configuration = new ReentryMethodConfiguration();
                    break;
            }

            return mrl;
        }
        #endregion

        #region Event Handlers

        #endregion

        #region Data Model Properties

        /// <summary>
        /// The human readable name of this Result List
        /// </summary>
        [G_NS.JsonProperty( Order = 1 )]
        public string ResultName { get; set; } = string.Empty;

        /// <summary>
        /// Globally unique identifier assigned to this MergedResultList.
        /// <para>String formatted as a UUID.</para>
        /// <para>Its is a fantastically bad idea to change this value after Construction.</para>
        /// </summary>
        [G_NS.JsonProperty( Order = 2 )]
        public int MergedId { get; set; } = 1; // Guid.NewGuid().ToString();

        /// <summary>
        /// The Tournament Method identifier to use to merge this Result List.
        /// </summary>
        [G_NS.JsonProperty( Order = 3 )]
        public MergeMethodType Method { get; set; } = MergeMethodType.SUM;

        /// <summary>
        /// The SCORE FORMAT COLLECTION to use while displaying scores for this MergedResultList
        /// </summary>
        [G_NS.JsonProperty( Order = 4 )]
        [Obsolete( "Use .Configuration.ScoreFormatCollectionDef instead." )]
        public SetName ScoreFormatCollectionDef { get; set; } = SetName.Parse( "v1.0:orion:Standard Score Formats" );

        /// <summary>
        /// The ScoreConfigName to use, from the SCORE FORMAT COLLECTION, while displaying scores for this MergedResultList
        /// </summary>
        [G_NS.JsonProperty( Order = 5 )]
        [Obsolete( "Use .Configuration.ScoreConfigName instead." )]
        public string ScoreConfigName { get; set; } = "Decimal";

        /// <summary>
        /// The list of Result Lists (in the form of <see cref="ResultListMember"/> to pull data from for this MergedResultList.
        /// </summary>
        [G_NS.JsonProperty( Order = 6 )]
        public List<ResultListMember> ResultListMembers { get; set; } = new List<ResultListMember>();

        /// <summary>
        /// Method specific Configuration
        /// </summary>
        [G_NS.JsonProperty( Order = 7 )]
        public MergeConfiguration Configuration { get; set; }

        #endregion

        #region Helper Properties
        /// <summary>
        /// Backwards pointer to the <see cref="MatchStructure"/> or <see cref="Tournament"/> (both of which implement the <see cref="IMergedResultListContainer"/> interface)
        /// that is holding this MergedResultList. Populated on deserialization.
        /// </summary>
        [G_NS.JsonIgnore]
        public IMergedResultListContainer Container { get; internal set; }
        #endregion

        #region Methods

        /// <inheritdoc />
        /// <exception cref="XApiKeyNotSetException" />
        /// <exception cref="DefinitionNotFoundException" />
        /// <exception cref="ScoposAPIException" />
        public async Task<ScoreFormatCollection> GetScoreFormatCollectionDefinitionAsync() {
            return await DefinitionCache.GetScoreFormatCollectionDefinitionAsync( this.Configuration.ScoreFormatCollectionDef );
        }

        #endregion
    }
}
